### PR TITLE
feat: add background image

### PR DESCRIPTION
**Pull request by doohanas**
## Changes

- feat: add background image in gabung desa-mitra section
- refactor:  change images file

## Preview

bg-gabung-desa-mitra

## Evidence
title: feat add a background image
project: Desa Digital
participants:  @adzharamrullah @maruf12 @Ibwedagama @ayocodingit

### CODE REVIEW

**Review by adzharamrullah — APPROVED** [review]

**Review by Ibwedagama — APPROVED** [review]

**Review by maruf12 — APPROVED** [review]

**Comment by ayocodingit** [comment]
hello kang @doohanas 
I found an issue in mozilla, the image failed to load.

open in chrome
image
open in mozilla
image

Please check, I'm afraid it's my browser that has an error :smile:

**Comment by abazer27** [comment]
cc: @ayocodingit 
image
its work on mine, what version are you using now kang?

**Comment by ayocodingit** [comment]
> cc: @ayocodingit image its work on mine, what version are you using now kang?

please check via deploy preview https://deploy-preview-41--desadigital.netlify.app/

**Comment by doohanas** [comment]
Hello kak @ayocodingit, please check again, whether the image has appeared or not? Thank you.

**Review by ayocodingit — APPROVED** [review]

**Pull request merged**
